"""
Generate a minimal OCR-style medical textbook PDF for pipeline testing.
Produces varied font sizes to exercise the font-size clustering path.
"""
import fitz

doc = fitz.open()

structure = [
    # (lines, base_font_size)
    # Each tuple is one page. Lines is a list of (text, size) tuples.
    [
        ("Chapter 1: Cardiovascular Physiology", 20),
        ("The study of cardiovascular physiology underpins clinical medicine.", 12),
    ],
    [
        ("1.1 The Heart as a Pump", 16),
        ("The myocardium contracts rhythmically due to action potentials propagated", 12),
        ("through specialised conduction tissue. The sinoatrial node generates", 12),
        ("approximately 60-100 impulses per minute under normal conditions.", 12),
    ],
    [
        ("1.2 Cardiac Output", 16),
        ("Cardiac output is defined as the product of stroke volume and heart rate.", 12),
        ("Normal resting CO is approximately 5 litres per minute in a 70 kg adult.", 12),
    ],
    [
        ("1.2.1 Factors Affecting Stroke Volume", 14),
        ("Preload, afterload, and contractility are the three primary determinants", 12),
        ("of stroke volume. Preload refers to the end-diastolic volume.", 12),
    ],
    [
        ("Chapter 2: Respiratory System", 20),
        ("Respiratory physiology governs ventilation and gas exchange.", 12),
    ],
    [
        ("2.1 Pulmonary Ventilation", 16),
        ("The movement of air into and out of the lungs is driven by pressure", 12),
        ("gradients generated by the respiratory muscles, primarily the diaphragm.", 12),
    ],
    [
        ("2.1.1 Dead Space and Alveolar Ventilation", 14),
        ("Anatomical dead space (approximately 150 mL in adults) does not", 12),
        ("participate in gas exchange. Alveolar ventilation = (Tidal volume - Dead space) x RR.", 12),
    ],
    [
        ("2.2 Gas Exchange", 16),
        ("Oxygen diffuses from alveoli (pO2 ~100 mmHg) into pulmonary capillary", 12),
        ("blood (pO2 ~40 mmHg). Carbon dioxide moves in the opposite direction.", 12),
    ],
    [
        ("Chapter 3: Renal Physiology", 20),
        ("The kidneys regulate fluid balance, electrolytes, and acid-base status.", 12),
    ],
    [
        ("3.1 Glomerular Filtration", 16),
        ("The glomerular filtration rate (GFR) averages 125 mL/min in healthy adults.", 12),
        ("Filtration occurs across the glomerular capillary wall driven by Starling forces.", 12),
    ],
    [
        ("3.2 Tubular Reabsorption and Secretion", 16),
        ("The proximal convoluted tubule reabsorbs approximately 65% of filtered", 12),
        ("sodium, water, glucose, and amino acids via active and passive transport.", 12),
    ],
]

for lines in structure:
    page = doc.new_page(width=595, height=842)
    y = 80
    for text, size in lines:
        page.insert_text((72, y), text, fontsize=size, fontname="helv", color=(0, 0, 0))
        y += size * 1.8

output = "test_medical.pdf"
doc.save(output)
doc.close()
print(f"Created {output} with {len(structure)} pages, {sum(len(p) for p in structure)} text blocks.")
